name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt-add-repository -y ppa:yubico/stable
          sudo apt-get update
          sudo apt-get install -qq libykpers-1-1 python3-pyscard swig libpcsclite-dev
          python -m pip install --upgrade pip
          pip install .

      - name: Run unit tests
        run: python setup.py test

      - name: Create source dist
        run: python setup.py sdist
